ARCADE/Controllers/ZaidimasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


using ARCADE.ViewModels;
using ARCADE.Repositories;

namespace ARCADE.Controllers
{
    public class ZaidimasController : Controller
    {
        public ActionResult Index()
        {
            return View(ZaidimasRepository.List());
        }

        public ActionResult Delete(int id)
        {
            var zaidimas = ZaidimasRepository.Find(id);
            return View(zaidimas);
        }

		[HttpPost]
		public ActionResult DeleteConfirm(int id)
		{
			try
			{
				ZaidimasRepository.Delete(id);
				return RedirectToAction("Index");
			}
			catch (MySql.Data.MySqlClient.MySqlException)
			{
				ViewData["deletionNotPermitted"] = true;
				var zaidimas = ZaidimasRepository.Find(id);
				return View("Delete", zaidimas);
			}
		}
	}
}

ARCADE/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ARCADE.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ARCADE/Pages/Index.cshtml.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ARCADE.Pages
{
    public class IndexModel : PageModel
    {
        public Zaidimas zaidimas { get; set; } = new Zaidimas();
        public List<Zaidimas> zaidimai { get; set; }
        public void OnGet()
        {
            zaidimai = GetZaidimai();
        }

        List<Zaidimas> GetZaidimai()
        {
            int count = 0;
            List<Zaidimas> zaidimai = new List<Zaidimas>();
            using (var reader = new StreamReader(@"../ARCADE/wwwroot/data/Zaidimai.csv"))
            {

                string line = "";
                while ((line = reader.ReadLine()) != null && count < 11)
                {
                    Zaidimas zaidimas = new Zaidimas();
                    string[] values = line.Split(',');
                    zaidimas.ID = values[0];
                    zaidimas.Pavadinimas = values[1];
                    zaidimas.Platforma = values[2];
                    zaidimas.Kaina = double.Parse(values[3]);
                    zaidimas.Zanras = values[4];
                    zaidimas.Bukle = values[5];
                    zaidimas.Nuotrauka = string.Format("~/images/Zaidimai/" + values[0] + ".jpg");

                    zaidimai.Add(zaidimas);
                    count++;
                }
            }

            return zaidimai;
        }
    }
}

ARCADE/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ARCADE.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ARCADE/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/news.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/css/ProductGridView.css" />
    </environment>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/hogwarts-legacy-cropped.jpg" alt="Hogwarts Legacy" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <a class="btn btn-default" href="https://www.hogwartslegacy.com/en-us">
                        Daugiau
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Witcher-edited.jpg" alt="Witcher" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <a class="btn btn-default" href="https://en.cdprojektred.com/news/a-new-saga-begins/">
                        Daugiau
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/ar1481.webp" alt="Elden Ring" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <a class="btn btn-default" href="https://en.bandainamcoent.eu/elden-ring/elden-ring">
                        Daugiau
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!------------------------------------------------------------------------>
<h1></h1>
<div class="container" >
    <div class="row">
        <div class="row">
            <div class="col-md-3">
                <h3>
                    Žaidimai
                </h3>
            </div>
            <div class="col-md-3" style="width: 27%; padding-top: 15px;">
                <!-- Controls -->
                <div class="controls pull-right hidden-xs" >
                    <a class="left fa fa-chevron-left btn btn-success" style="background-color:#166c6c" href="#carousel-example" data-slide="prev"></a>
                    <a class="right fa fa-chevron-right btn btn-success" style="background-color:#166c6c"href="#carousel-example"data-slide="next"></a>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
        <div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
            <div class="carousel-inner">
                @for (int i = 0; i < Model.zaidimai.Count / 4 + 1; i++)
                {
                    string cl = "item";
                    if (i == 0)
                    {
                        cl = String.Format(cl + " active");
                    }
                    int rowLength = 4;
                    if (i * 4 + 4 > Model.zaidimai.Count)
                    {
                        rowLength = Model.zaidimai.Count - i * 4;
                    }
                    <div class="@Url.Content(cl)">

                        <div class="row">
                            @for (int j = 4 * i; j < i * 4 + rowLength; j++)
                            {
                                <div class="col-sm-3" style="width:24%">
                                    <div class="col-item">
                                        <div class="card" style="border: 3px solid #eeeeee; width:105%;">
                                            <img src="@Url.Content(Model.zaidimai[j].Nuotrauka)">
                                            @{
                                                string name = Model.zaidimai[j].Pavadinimas;
                                                if (name.Length > 20)
                                                {
                                                    name = string.Format(name.Substring(0, 20) + "...");
                                                }

                                                <h1 style="font-size:20px"> @name </h1>
                                            }
                                            @{
                                                double price = Model.zaidimai[j].Kaina;

                                                <p class="price">
                                                    @string.Format(String.Format("{0:0.00}", Model.zaidimai[j].Kaina))€
                                                </p>
                                            }
                                            <p><button>Įdėti į krepšelį</button></p>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</div>



<!------------------------------------------------------------------------>


<div class="newsarticle">
    <img class="newsimage" src="/images/rocket.jpg" alt="Rocket League">
    <div class="newstext">
        <h2>„Rocket League“ balso pokalbių funkcija grįžta</h2>
        <p>
            Šios funkcijos žaidėjai labai prašė po to, kai „Psyonix“ pašalino ją iš žaidimo prieš šešis mėnesius
        </p>

        <a asp-page="/News/FirstNew" class="2">Skaityti daugiau</a>

    </div>
</div>

<div class="newsarticle">
    <img class="newsimage" src="/images/lost ark.jpg" alt="Lost Ark">
    <div class="newstext">
        <h2>Lost Ark - Free to Play MMO</h2>
        <p>
            Pasinerkite į nuostabią Arkesijos istoriją. Išbandykite save kovoje, išmokite pritaikyti savo kovos stilių įvairiomis charakterių klasėms ir apsaugokite Arkos galią nuo tamsiųjų jėgų.
        </p>

        <a href="https://www.playlostark.com/en-us">Žaisti</a>

    </div>
</div>

</html>
@Url.Action("Index", "Zaidimas")